version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - zk
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    networks:
      - zk
      - kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db:
    image: postgres:11
    restart: always
    networks:
      - db
    ports:
      - "65432:5432"
    # volumes:
    #   - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME

  api:
    build:
      context: .
      dockerfile: ./aragon/api/Dockerfile
    restart: always
    depends_on:
      - db
      - broker
    networks:
      - default
      - db
      - kafka
    ports:
      - "8041:8000"
    volumes:
      - ./aragon:/usr/code/aragon
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}"
      KAFKA_RULES_TOPIC: "rules"
      KAFKA_BOOTSTRAP_SERVERS: "broker:9092"

  worker:
    build:
      context: .
      dockerfile: ./aragon/worker/Dockerfile
    restart: always
    depends_on:
      - broker
    networks:
      - kafka
    volumes:
      - ./aragon:/usr/code/aragon
    environment:
      PYTHONUNBUFFERED: 1
      KAFKA_RULES_TOPIC: "rules"
      KAFKA_BOOTSTRAP_SERVERS: "broker:9092"

networks:
  zk:
    driver: bridge
  kafka:
    driver: bridge
  db:
    driver: bridge
# volumes:
#   dbdata:
